name: se7ety
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.5
  cuberto_bottom_bar: ^3.0.0
  date_picker_timeline: ^1.2.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  gap: ^3.0.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.7
  intl: ^0.18.0
  lottie: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/screen1.png
    - assets/screen2.png
    - assets/screen3.png
    - assets/hello.png
    - assets/card.png
    - assets/doc.png
    - assets/me.jpg
